### ISSUE TITLE
User agent list seems to be a bit out dated

### ISSUE THREAD

**Issue by BoudewijnZwart** [fake-useragent/fake-useragent#287]
Hello,

First off, I really like this package and I want to use it. However, the list of user agents that come with this packages seems to contain a lot of out dated user agents. The source for the user agents (techblog.willshouse.com) also seems to be offline. The last version I can find from web.archive.org is from 30-08-2023.

The option to update the current list using a spider is really nice but it seems to also have broken down. It depends on a cached version of the techblog.willshouse.com (https://webcache.googleusercontent.com/search?q=cache:https%3A%2F%2Ftechblog.willshouse.com%2F2012%2F01%2F03%2Fmost-common-user-agents%2F) that also does not seem to work anymore.

I think their are currently better and more up-to-date sources for a list of user agents. For instance, this one seems to contain a lot of recently used user agents that you can query for the browser and version of that browser you would like: https://user-agents.net/download?browser=chrome&version=121-0&limit=10. This website has an API endpoint from which you can easily get the user agents.

The only downside is that it does not contain statistics on how often they are used. Still, I feel like this would really make this package more usable. 

Do you agree? If so, I can make a PR to add this feature.

**Comment by melroy89** [comment]
Correct. The source is indeed from techblog.willshouse.com, which is offline and outdated by now. 

The reason I was using google cache was because the official site was hosted behind a Cloudflare anti-bot system, unable to scrape the file. Anyhow, yes I need a better source for more up to date user agents again.

Yes, feel free to create a PR and use the JSON API to retrieve the data of top 10 browsers or so. We also might want to include mobile user-agents and create a special option to only get a desktop user-agent, mobile user-agent or both (currently you only get a random desktop user-agent, since techblog.willshouse.com didn't include mobile user-agents).

**Comment by melroy89** [comment]
Fixed by: https://github.com/fake-useragent/fake-useragent/pull/290

**Comment by melroy89** [comment]
FYI. There is a new release now: https://github.com/fake-useragent/fake-useragent/releases/tag/1.5.0

**Comment by melroy89** [comment]
You can try to latest version now (2.0.0). Update via:

```sh
pip install --upgrade fake-useragent
```
