### ISSUE TITLE
I randomly selected user agents and removed duplicates, and there were only 79 of them.

### ISSUE THREAD

**Issue by cplasfwst** [fake-useragent/fake-useragent#333]
```py
# get_useragent.py
from fake_useragent import UserAgent

def get_random_useragent():
    ua = UserAgent()
    print(ua.random)


if __name__ == "__main__":
    for _ in range(10000):  
        get_random_useragent()

````
I tried many times, and only a few dozen quantities were unique.

**Comment by int33h** [comment]
Also the file browsers.json contains too many duplicates which negatively impacts the random choice

**Comment by melroy89** [comment]
You are right.. There are a lot of duplicates for some reason.. @BoudewijnZwart Could you help us here?? 

Look at the amount of duplicate UA strings introduced in the browsers.json file:

![image](https://github.com/user-attachments/assets/45dd9a28-c002-4aef-b500-3c38d3498260)

**Comment by melroy89** [comment]
ps. (Could we also automate the user agents download in some script, so we can earlier update the data, remove duplicates, trim the strings, etc. etc.)

**Comment by BoudewijnZwart** [comment]
Hmm I see. Yeah I will take a look and try to update the list tomorrow probably. The automation would be nice but will take some more time.

**Comment by melroy89** [comment]
Maybe at this point writing a simple python script that download multiple types of data from: https://user-agents.net/download, trim the strings, remove duplicates, etc. Will actually starting to look like less work then manually trying to do this.

What are the options you provided in this Download User Agents form to get the data we now have? Since I can't just hit "Find User Agents", that will say `Sorry, but you must specify at least one property.`... So I'm also curious about how you filled in the search form and how we could get more unique user agent strings in general.

**Comment by BoudewijnZwart** [comment]
Yeah I agree. I have a Python script that I used to send requests to the `user-agents.net` API. I specify a browser, a version and the maximum number I want back. The script does some cleaning of the data and putting it in the right format. I does not yet remove duplicates, but I can add this. 

The downside is that you can only send 2 requests per day I think. So you cannot update all the browsers in one go. I can make a PR with the Python script I am using.

**Comment by melroy89** [comment]
~~PR is in the making to tackle this issue: https://github.com/fake-useragent/fake-useragent/pull/356~~

**Comment by melroy89** [comment]
https://user-agents.net/download "API" is very restrictive too bad. I was trying to get in contact with the creator of this website, too bad he/she didn't respond back. Meaning we now need to deal with the very restrictive rate limit imposed on us. 

My ideas thus far were:

1. At some point you want to start-over (remove the file) and construct the file from scratch with the latest information, instead of appending. What interval I don't know yet, but it does make sense to me to clean-up the old agents and trying fetching the latest most use agents from the site above.
2.  In-complete user-agent file shouldn't be deployed. We want to keep track of the file (by saving the json file to another path, maybe still store it in git or not.. Benefit of JSONlines is we can actually easily extend it), until we have all the different browsers user agent strings. Only then we are ready to deploy it do production. See also point 4.
3.  If for some reason user-agents.net is down or down forever, we shouldn't remove the JSONlines file of course. We need to find an alternative first, so we need to be robust for this situation as well.
4.  The main branch should be able to deploy to production at all times. We can't have half baked JSONlines file in the src/fake_useragent/data. Meaning, the git `main` branch should always contain a valid and full JSONlines file and we should be able to create a new pip package release whenever we need or want to.

**Comment by sebastian-correa** [comment]
Hey @melroy89, what do you think about making the script find the latest N versions of each browser and always rewrite the file so that it has these last N? Maybe we can keep the last 30 versions, as I'd suspect the file would be quite small anyways. This would solve point 1.

I'm not sure I followed point 2. The script will only rewrite the file if it's done scraping. This would also make 3 and 4 a non-issue, as the file won't be overridden if the process doesn't finish.

I think running this script maybe monthly in an action that opens PR to `main` would help us with this.

BTW, I'm trying to figure out how to make as single API call to get a version range, but I think that's not possible... About the timeouts, I think we could use the `backoff`. I'll keep you posted. I think using [this](https://github.com/mdn/browser-compat-data/tree/main/browsers) (which is what backs browsers.fyi) might be of help, cause it lists all versions in order.

**Comment by melroy89** [comment]
> Hey @melroy89, what do you think about making the script find the latest N versions of each browser and always rewrite the file so that it has these last N? Maybe we can keep the last 30 versions, as I'd suspect the file would be quite small anyways. This would solve point 1.

That sounds as a good start. But I'm afraid that even latest N versions for each browser will get you rate limited already, that is how heavy this rate limit is on https://user-agents.net website..

> I'm not sure I followed point 2. The script will only rewrite the file if it's done scraping. This would also make 3 and 4 a non-issue, as the file won't be overridden if the process doesn't finish.

Sorry if I was unclear. What I try to explain is basically we want reproducibility. Thus repeatable by executing the script later again, it should result in the same file. Since I'm afraid we can't run the script in 1 execution cycle due to the very restrictive rate limit. 

Thus it might be a good idea to have 1 "fully populated" json (JSONlines) file in the data directory like now, which can be deployed to pip whenever we want.
And another temporary JSONlines file that is not fully populated yet, so some sort of  "cache" basically to it will be appended with more information the next time it can be ran again.

> I think running this script maybe monthly in an action that opens PR to `main` would help us with this.

That was also my idea, so I'm in for that one! And yes this "temporary JSON" file could then be used by GitHub Actions. Could even be done automatically without PR, we it doesn't directly change the JSONlines file from the data directory. 

So to summarize:

- 1 JSONline files fully filled as expected and ready to deploy to production and to Pip package manager. This file contains all the browsers we want.
- Another JSONline files that act as a temporary/"cache" JSONfiles, not yet fully filled yet. Which can be extended automatically by GitHub Actions.
- Only when we have now filled enough user agents in the JSONfiles file. We can make the temporary/"cache" JSONfiles the new JSONline file in the data directory. 

This is just one of many solutions I guess how to deal with this problem, where the rate limit is so harsh. 

> BTW, I'm trying to figure out how to make as single API call to get a version range, but I think that's not possible... About the timeouts, I think we could use the `backoff`. I'll keep you posted. I think using [this](https://github.com/mdn/browser-compat-data/tree/main/browsers) (which is what backs browsers.fyi) might be of help, cause it lists all versions in order.

You can still peek into the closed PR: https://github.com/fake-useragent/fake-useragent/pull/356/files#diff-13938f013ab85897f9d4a73e75bca77fdde8b36def89cf719e28d9f2978ab387

Although this is not the final solution, it might get you started.

**Comment by sebastian-correa** [comment]
@melroy89, I've been doing some research cause, yes, online providers are few and far between and have stringent limits, which are annoying to work around. So far, I have these insights:
1. All, if not most, entities that have access to UA data get it from tracking pixels or by owning large websites and building DBs from traffic data.
1. Neither https://user-agents.net/ nor https://useragentstring.com/pages/api.php (nor any other I found, actually) allows good filtering ability. I think having the script get the last N versions would look like this:
    1. Fetch all versions from [MDN's repo](https://github.com/mdn/browser-compat-data/tree/main/browsers).
    2. Filter down to the last N.
    3. Hit https://user-agents.net/ once per version that's not already in our file.
        - We can give [backoff](https://github.com/litl/backoff) a try here to work around the rate limits, though that might make the GH Action run for very long times. This might be an issue but, as far as I understand from [here](https://docs.github.com/en/actions/administering-github-actions/usage-limits-billing-and-administration#about-billing-for-github-actions), public repos have free GitHub Action usage.
        - Your 2 file idea could work if the scraping takes too long to run, as we'd have the action commit partial JSONlines that we'd then merge and duplicate for a release. We'd need to skip scraping browsers/platforms/versions that are already in these partial files, but that's doable.
    5. Build the file and open a PR/do a release.
2. I found the [`user-agents`](https://github.com/intoli/user-agents) JS library, which is equivalent to ours, but seems to be maintained by a large proxy provider. They do daily releases and host [the UA file](https://github.com/intoli/user-agents/blob/main/src/user-agents.json.gz) in their repo. I wouldn't using without asking, but it might be an option! If you look at their [update process](https://github.com/intoli/user-agents/blob/main/src/update-data.ts) or [this](https://intoli.com/blog/user-agents/) blogpost of theirs, it seems to be that they just query some DB they own and update the file.

In the future, it might be a good idea to add code to have the `FakeUserAgent` retrieve a newer, up-to-date file from a remote source and only use the bundled file as a backup. But that's for another day.

I'll look into the first option with `backoff` to see how it goes while I wait for your comments on the second.

Edit: I think I finally see what you meant by throttling... I'm not even able to request more than 1 version in the span of some minutes, even by hand...

**Comment by melroy89** [comment]
Thanks for your research! And thank you for commenting. Some takeaways:

> We can give [backoff](https://github.com/litl/backoff) a try here to work around the rate limits, though that might make the GH Action run for very long times. This might be an issue but, as far as I understand from [here](https://docs.github.com/en/actions/administering-github-actions/usage-limits-billing-and-administration#about-billing-for-github-actions), public repos have free GitHub Action usage.

Even tho we do have "free" Actions there are still limits of course, like: "Workflow run time - Each workflow run is limited to 35 days. If a workflow run reaches this limit, the workflow run is cancelled. This period includes execution duration, and time spent on waiting and approval.". 

After which you can no longer use GitHub Action. This is not how you use GitHub action, if you want to wait, you wait outside of GitHub Action eg. via a `cronjob`, and trigger later again. Like I mentioned before this would be the "cache file" which you will expend upon. That is how you will never hit these limits.

> In the future, it might be a good idea to add code to have the `FakeUserAgent` retrieve a newer, up-to-date file from a remote source and only use the bundled file as a backup. But that's for another day.

No, this is what we did in the past 😢 . Which caused tons of issues, like people behind proxies. People who got rate-limited by the public source. When the source is behind Cloudflare, you will get tons of issues like anti-bot protections. Issues like:

- https://github.com/fake-useragent/fake-useragent/issues/163
- https://github.com/fake-useragent/fake-useragent/issues/58
- https://github.com/fake-useragent/fake-useragent/issues/239
- https://github.com/fake-useragent/fake-useragent/issues/106
- https://github.com/fake-useragent/fake-useragent/issues/101
- https://github.com/fake-useragent/fake-useragent/issues/78
- https://github.com/fake-useragent/fake-useragent/issues/62
- https://github.com/fake-useragent/fake-useragent/issues/157

I'm **not** going back to that.... If you could imagine all the pain we went through.

**Comment by sebastian-correa** [comment]
> No, this is what we did in the past 😢 . Which caused tons of issues, like people behind proxies. People who got rate-limited by the public source. When the source is behind Cloudflare, you will get tons of issues like anti-bot protections.

I meant retrieving our own file, optionally. This way, users don't need to keep the package up to date and. But given that history and the fact that we can do patch releases to release new files (which should be compatible with almost all version specs), you're right; we shouldn't go down that path again.

> After which you can no longer use GitHub Action. This is not how you use GitHub action, if you want to wait, you wait outside of GitHub Action eg. via a cronjob, and trigger later again. Like I mentioned before this would be the "cache file" which you will expend upon. That is how you will never hit these limits.

Did you give speaking with the [`user-agents`](https://github.com/intoli/user-agents) guys a think?

I wouldn't want to pollute `main` with these partial commits/files. The Action running the script with single `browser`/`version` combos should probably add the partial files into a separate branch. You didn't get a response from [info@user-agents.net](mailto:info@user-agents.net) no?

**Comment by melroy89** [comment]
> > 
> 
> Did you give speaking with the [`user-agents`](https://github.com/intoli/user-agents) guys a think?

I did check the repo, and this script seems to create this `.json.gz` user-agents file from that repository: https://github.com/intoli/user-agents/blob/fbffe130b6b9de9cd8fda7f5bfde3977feeaf5ab/src/update-data.ts#L46

This script seems to use some kind of dynamoose (AWS) database using `scan` to retrieve data from this database. But this job seems to be running on CircleCI: https://github.com/intoli/user-agents/blob/fbffe130b6b9de9cd8fda7f5bfde3977feeaf5ab/.circleci/config.yml#L135

So yea, no clue where they get this data from. But original data source is definitely unknown.
Most likely they are using a very high traffic website, and collecting user-agents from that? And do some post-processing on the data. But sure, we could ask them.

But I also run several sites, I actually also have a database of user-agent strings myself from Nginx logs (stored in InfluxDB). I could do some same trickery maybe.

> I wouldn't want to pollute main with these partial commits/files. The Action running the script with single browser/version combos should probably add the partial files into a separate branch. 

Yes indeed, so it's better to use a separate branch. This is a good best practice since there is no alternative.

Alternatively ( 😆 ), you can leverage some registry (like Jfrog Artifactory or other kind of generic registry). I'm afraid GitHub only provides a package registry. While this is nice, it's not applicable for generic files like we now have, so we are back to using a separate branch:

![image](https://github.com/user-attachments/assets/a923820a-ae7a-469b-993e-c01c597ebcfc)


> You didn't get a response from [info@user-agents.net](mailto:info@user-agents.net) no?

I didn't sent a mail yet. So no.

**Comment by sebastian-correa** [comment]
Yes, that's what they do. They collect the UAs from their sites/proxy service and the package is just a thin wrapper around the JSON (like ours), and they get the JSON by a simple query to the DB.

> But I also run several sites, I actually also have a database of user-agent strings myself from Nginx logs (stored in InfluxDB). I could do some same trickery maybe.

That could work! Though it might be a bigger undertaking than just updating the package just now. In the meantime, is it easy for you to figure out how many unique UAs per day/week/month you have in that DB?

~I'll send the email and chat with the `user-agents` people and be back with news ASAP.~ Comms out. Will be back with news hopefully soon.

**Comment by sebastian-correa** [comment]
Well, I did not get a reply to the issue I opened in the `user-agents` repo (https://github.com/intoli/user-agents/issues/79) or to the email I sent to user-agents.net.

After reading Intoli's license, I think we should be able to use their data. If they disagree and don't want us to, we can rethink our strategy (either using your data or trying the complicated approach with user-agents.net).

Let me know what you think!

**Comment by melroy89** [comment]
Agreed. License seems to be fine 2-Clause BSD License. I also never got a reply from user-agents.net in the past, which is a shame!

Thanks for helping me though.

In our case we would like to read the JSON file into memory, I believe untar/gzing the file upfront would make sense to increase the start-up times when using Python. So we might just to store the file in JSON format in git. ANd we also might want to convert their file into JSONfiles format as well.

The only down-side is if we switch again (again, again) to this new source. Be aware we will need to remap the meta-data to the existing meta data we now have (beautified):

```json
{
  "useragent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0 Trailer/92.3.3357.27",
  "percent": 100,
  "type": "pc",
  "system": "Edge 121.0 Windows",
  "browser": "edge",
  "version": 121,
  "os": "win10"
}
```
Their format is:

```json
{
    "appName": "Netscape",
    "connection": {
      "downlink": 6.35,
      "downlinkMax": null,
      "effectiveType": "4g",
      "rtt": 100,
      "type": "cellular"
    },
    "language": "en-US",
    "platform": "Linux armv81",
    "pluginsLength": 0,
    "screenHeight": 800,
    "screenWidth": 360,
    "userAgent": "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36",
    "vendor": "Google Inc.",
    "viewportHeight": 671,
    "viewportWidth": 360,
    "weight": 0.0004368632895782006,
    "deviceCategory": "mobile"
 }
 ```
 
 Besides the fact they use JSON instead of JSONlines (that is an easy fix), the other big difference is the whole structure itself. 
 Hopefully we are able to match their keys to our keys: `percent`, `type`, `system`, `browser`, `version` and `os`..?

**Comment by melroy89** [comment]
OK, I created a converter myself, this ticket is taking too long now. https://github.com/fake-useragent/fake-useragent/blob/main/ua-converter/ua_convert.py

This will convert the data from intoli to jsonlines with additional information. The output is something like this:

```json
{"useragent": "Mozilla/5.0 (Linux; Android 5.1.1; KFDOWI) AppleWebKit/537.36 (KHTML, like Gecko) Silk/108.15.4 like Chrome/108.0.5359.220 Safari/537.36", "percent": 0.051185867765394924, "type": "tablet", "device_brand": "Amazon", "browser": "Amazon Silk", "browser_version": "108.15.4", "browser_version_major_minor": 108.15, "os": "Android", "os_version": "5.1.1", "platform": "Linux armv8l"}
{"useragent": "Mozilla/5.0 (iPhone; CPU iPhone OS 18_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1.1 Mobile/15E148 Safari/604.1", "percent": 0.06813698994201217, "type": "mobile", "device_brand": "Apple", "browser": "Mobile Safari", "browser_version": "18.1.1", "browser_version_major_minor": 18.1, "os": "iOS", "os_version": "18.1.1", "platform": "iPhone"}
{"useragent": "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36", "percent": 0.051441313637680605, "type": "mobile", "device_brand": "Generic_Android", "browser": "Chrome Mobile", "browser_version": "131.0.0.0", "browser_version_major_minor": 131.0, "os": "Android", "os_version": "10", "platform": "Linux armv81"}
{"useragent": "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36", "percent": 0.06264256343016018, "type": "mobile", "device_brand": "Generic_Android", "browser": "Chrome Mobile", "browser_version": "131.0.0.0", "browser_version_major_minor": 131.0, "os": "Android", "os_version": "10", "platform": "Linux armv81"}
{"useragent": "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36", "percent": 0.054767908471821336, "type": "mobile", "device_brand": "Generic_Android", "browser": "Chrome Mobile", "browser_version": "131.0.0.0", "browser_version_major_minor": 131.0, "os": "Android", "os_version": "10", "platform": "Linux armv81"}
{"useragent": "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36", "percent": 0.05697442655537689, "type": "mobile", "device_brand": "Generic_Android", "browser": "Chrome Mobile", "browser_version": "131.0.0.0", "browser_version_major_minor": 131.0, "os": "Android", "os_version": "10", "platform": "Linux armv81"}
{"useragent": "Mozilla/5.0 (iPhone; CPU iPhone OS 17_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Mobile/15E148 Safari/604.1", "percent": 0.05653145233988486, "type": "mobile", "device_brand": "Apple", "browser": "Mobile Safari", "browser_version": "17.6", "browser_version_major_minor": 17.6, "os": "iOS", "os_version": "17.6.1", "platform": "iPhone"}
```

**Comment by sebastian-correa** [comment]
Sorry @melroy89, life got in the way to be honest. My bad. I was going to work on this now but it seems to be mostly done! I'll use the time to work on a PR to have a GitHub action do this automatically.

**Comment by melroy89** [comment]
The script is done and the fake-useragent changes are also done locally (more or less).

The problem is that my converter is taking forever because I use `ua_parser` package to parse the user-agent strings to extract all the details. This [ua_parser package](https://github.com/ua-parser/uap-python) is very useful actually, but comes at a cost.

Which I then store into the JSONlines. But despite using `ThreadPoolExecutor` (even increasing the `max_workers`), it doesn't seem to scale very well... Python -,-

Processing 52kb of date takes around 1 minute and 30 seconds **_without_** threadpool.  
**With** ThreadPoolExecutor, for some reason it takes longer!? 2 minutes and 6 seconds the same amount of 52kb data.

The total JSON file I downloaded is 4.9MB. 4900 / 52 ~= 141 minutes. So let's say around 2.5 hours..

**Comment by sebastian-correa** [comment]
Yeah, noticed this... Maybe we can extract the pieces of code necessary to parse the data we need from the `ua_parser` library.

For now I'm assuming this will be solved at some point and focusing on modularizing the script and running an action with it. I'll push a branch for you to check when I have something presentable :).

Edit: my suggestion is unreasonable, but they do have the `Domain` argument which might help.
Edit 2: check https://github.com/fake-useragent/fake-useragent/tree/update-uas-action.

**Comment by melroy89** [comment]
PR created for now: https://github.com/fake-useragent/fake-useragent/pull/400

.. Let's see if I have a faster machine to do the processing for now 😆

**Comment by melroy89** [comment]
> Edit: my suggestion is unreasonable, but they do have the `Domain` argument which might help.

We are now actually using all 3 domains: user-agent, device and os... :)

**Comment by sebastian-correa** [comment]
I'll look at the PR tomorrow night. I was going to comment on the name changes and incompatibility; this might mean we need to release a `v2`. I pushed a branch to the repo with some changes to some scripts (which now needs to be rebased, I'll handle that).

Can you check the permissions requested [here](https://github.com/peter-evans/create-pull-request?tab=readme-ov-file#workflow-permissions)?

**Comment by melroy89** [comment]
Yea we definitely want to call it `v2` now. However, the API is still compatible I believe.

You can still do `ua.firefox` or `ua.chrome` for example :). And new is: `ua.edge` and: `ua.opera`. Only some user-agents like `ua['google chrome']` or something fancy like that. Won't work anymore. That is now just `ua.chrome` or `ua.Chrome` or `ua['Chrome Mobile']`

**Comment by sebastian-correa** [comment]
That I agree. Not sure if the file itself is part of the public API, given we ship it with the package... If not (which is a decision we make I think), then `v1` should be fine.

I kept on reading and it _might be worth it_ to have a `useragent-updated` app registered to make these changes. Not sure if you have access to create one for the organization (guide [here](https://docs.github.com/en/apps/creating-github-apps/registering-a-github-app/registering-a-github-app#registering-a-github-app)).

**Comment by melroy89** [comment]
> That I agree. Not sure if the file itself is part of the public API, given we ship it with the package... If not (which is a decision we make I think), then `v1` should be fine.

Uh there is besides the `ua.firefox`, etc. also  `ua.getChrome`,  `ua.getFirefox`.. But that is about it regarding the API.

Yes, the JSONfiles is part of the package (thank god): https://github.com/fake-useragent/fake-useragent/pull/400/files#diff-c20ec3d5675d94be884be7d3cde83f367be1efc9b25df9fc2f052353d5f23aa3
EDIT: So this jsonl file in the data directory is packaged with the pip package.

Anyhow, I still need to fix the unit-tests.

GitHub App is not needed. If you want push permissions or pull requests permissions, you can do so via GItHub Actions itself, by setting correct permissions for the built-in access token: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token#defining-access-for-the-github_token-permissions

Like for example in your workflow file you will write at the top somewhere:

```yaml
permissions:
  contents: write
  pull-requests: write
```

**Comment by melroy89** [comment]
PR is ready: https://github.com/fake-useragent/fake-useragent/pull/400

**Comment by melroy89** [comment]
Congratz. It's related: https://github.com/fake-useragent/fake-useragent/actions/runs/12168320659/job/33938947789

And: https://pypi.org/project/fake-useragent/

`2.0.0` tag is released.
